CREATE TABLE users(
	userID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    userName VARCHAR (125) NOT NULL,
    userEmail VARCHAR (125) NOT NULL,
    userUid VARCHAR (80) NOT NULL,
    userPwd VARCHAR (155) NOT NULL
);